version: "3"

services:
  app:
    container_name: client_manager_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    command: sh -c "npm install && ts-node setup.ts && npx nodemon main.ts"
    networks:
      - client_manager_api
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/client_manager_api
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: database-mysql
    restart: always
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE:client_manager_api
      - MYSQL_PASSWORD:root
    ports:
      - "3306:3306"
    networks:
      - client_manager_api

networks:
  client_manager_api:
    name: client_manager_api
    driver: bridge
